### ISSUE TITLE
Concept Flow – GDPR and Project Data Sharing

### ISSUE THREAD

**Issue by Cornelieke-IHIW18** [IHIW/IHIW_Management#165]
Related to #114 and #118

**Personal**
Sign Up > Add personal and professional information > Give permission to store your personal (and busi-ness) data  [checkbox]  (because you have no choice)
Change your data > no consequences
Uncheck/revoke permission = Request removal via email > admin deletes the account (but not any uploaded project data) 

**Project Data Sharing**
Sign into IHIW database > Subscribe to Project (maybe ask permission to share your data with project(s) here? Or just tell them that their file will be shared with etc…) > Upload file 
Project Leaders > Ask them if the data submitted to their project can be shared with other project leaders if the workshop chairs send a request.

**Comment by bmatern** [comment]
- Password reset screen: add the checkbox.
  - For existing&active / new / inactive users.
- No "persistence" or no need to track if permission has been given.
- Question - how is an account "disabled" or deleted? An option for this on the "Settings" page for my account.
  - What do we do with existing data? Existing projects or labs? Do they need to be assigned to another person

**Comment by bmatern** [comment]
- 2 options:
  - to just delete personal data, 
  - or delete personal data and all submitted workshop data.

**Comment by bmatern** [comment]
For personal data, when we are asked to delete.
-delete persoanl information, keep the labcode. Overwrite the userid (which is the email address) with a lab id.
-and clear the phone number

**Comment by bmatern** [comment]
Split this into tickets:

Here's one plan:
- Add text to password reset screen (I think the text doesn't need to be on the password reset screen)
   - https://staging.ihiws.org/reset/request is the password "reset" screen. not the change password screen
- Login: Check the "user consent" and if it's null
   - redirect to the permission screen. (This is an intermediate screen)
   - This is tricky because: the user token gives god rights, and we "should" give a token with limited rights.
- For existing users: Something at the login screen? Every time you login? 
   - We need to do this permission email soon.
   - Hard to do a mass-delete of passwords. Becuase that looks like security breach.
   - I propose a field called "user_consent" under ihiw_user. It's a boolean, default to Null.

An easier plan:
- Just have a checkbox on login screen. EVERY TIME you log in you must accept the consent box.
- A good first step.

**Comment by bmatern** [comment]
The easier plan was implemented. Login screen forces a checkbox at each login, provides link to policy.
