### ISSUE TITLE
Set up IDE @inemp and @FPR

### ISSUE THREAD

**Issue by ghost** [IHIW/IHIW_Management#26]
To make Ioannis and myself involved in the project, the IDE (intelliJ) needs to be installed.
Also a local database needs to be installed with some data, otherwise you can't even log in to the app.

I choose IntelliJ since it works without too much configuration and Eclipse did not work.
Also the PIRCHE group is using it.

**Comment by FPR-GenDx** [comment]
For windows, the easiest to get a JDK is to go to: https://adoptopenjdk.net/ and download version 8.
In intelliJ this is then linked as a JDK.

Then git needs to be installed, I choose to install tortoiseGit as well, since windows the commandline is not friendly.

The source is then downloaded from GitHub, and loaded. a build configuration is added in IntelliJ to run it and then the project builds.

**Comment by FPR-GenDx** [comment]
Since we're working on windows, I choose to use the windows installer for MariaDB: https://downloads.mariadb.org/mariadb/10.3.13/ (link without registration).
It also installs HeidiSQL to edit the databases.

To make it work, I removed the password from the root account, and created a database named ihiwManagement.

By runnin the app locally once with faker enabled, it fills the database with some random values. Also it created a default 'user' and 'admin' account, so it is possible to log in.
Then disable faker again.

**Comment by FPR-GenDx** [comment]
The angular part is still not working correctly, it builds with npm. the ng commandline does not work, it fails.
