### ISSUE TITLE
Dropdown for countries in user registration

### ISSUE THREAD

**Issue by cyt-mn** [IHIW/IHIW_Management#4]
This is to ensure the country code used for generating a lab code is valid.

**Comment by espierin** [comment]
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

**Comment by FPR-GenDx** [comment]
Now the plan is to use a library for country codes like: https://www.npmjs.com/package/i18n-iso-countries/.

The database will not be changed, full country name will be there.
Forms for user registration and lab edit will have drop down with all coutries.

The country codes will for now only be used to generate the labcodes, not for anything else.

**Comment by FPR-GenDx** [comment]
using country-code-lookup I added a dropdown with the country names in the register user component.

**Comment by cyt-mn** [comment]
Please send also the country ISO code to the backend and use it for creating the lab code

**Comment by Cornelieke-GenDx** [comment]
Tested by creating a new user without a lab code. The lab code is correctly generated, using the 3 letter country code and the first 3 letters of the user's last name.
The country list itself is not ordered alphabetically though, maybe we should fix this.

**Comment by espierin** [comment]
remove the "the" from the front (eventually move to back) and sort alphabetically

**Comment by Cornelieke-GenDx** [comment]
When registering a new user without a lab code, the country dropdown is now alphabetically ordered and the "the" is behind the name. The lab code is generated as it should.
I did notice however that when editing an existing lab, the country field does not have the dropdown and if you change the country of an existing lab, the code stays what it was. It does not seem to be a problem though, because it is unlikely that people will move their labs to another country I guess.

**Comment by cyt-mn** [comment]
@Cornelieke-GenDx good point. I'd suggest filing a ticket to keep this in mind. However, as you said, it is probably a less common use case. So we consider this as approved!?

**Comment by Cornelieke-GenDx** [comment]
As far as I'm concerned, yes, #4 approved. Maybe wait for @espierin to have a look as well.
I'll create a ticket for the _edit a lab country field_ thingy.

**Comment by espierin** [comment]
Checked on staging and approved.
