### ISSUE TITLE
Converter scripts should create upload entry for converted file in MGMT app

### ISSUE THREAD

**Issue by cyt-mn** [IHIW/IHIW_Management#99]

**Comment by bmatern** [comment]
-Needs some work on Authority, in the rest endpoint. 
-the converted file should be the same user that uploaded the other file, instead of the AWS lambda user.

**Comment by bmatern** [comment]
Challenges-

-Creating an upload object without actually uploading a file, it already exists.
-How to assign the user ID to the previoius upload? Could use the same user as the previous upload but thats not great for security.

Probably - create new endpoint that only allows system user. Current endpoint is accessible by any user. It uses the system user, or must have the "validation" role.

**Comment by inemp** [comment]
Could you give a bit more details? It is still unclear to me, what this ticket is about

**Comment by bmatern** [comment]
Yep no problem, sorry I missed the comment. The HAML converter accepts an uploaded .csv file and converts it into a .haml (xml) file. The .haml file is saved on the s3 storage, and it has the same filename as the original file with a .haml added at the end.

The problem is, the management website can't see the converted file, because there is nothing in the "upload" table that refers to the new haml file.  We want to create a new Upload entry that refers to the converted .haml file. 

Solution is probably this:
1) Create a REST endpoint in the UploadResource, accessible by a user with the ROLE_VALIDATION. It can create a new upload for the converted file. It will create a new upload entry, but will not actually upload a file.

2) Change haml converter to use this rest endpoint when it converts the file.

This is a nice feature because we'll be adding other types of file conversion soon.
